# Uncomment the next line to define a global platform for your project
# platform :macosx, '10.12'

target 'ConsoleProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ConsoleProject

end
